"""Add prologue to scenario

Revision ID: 3f8b1a9c2e0d
Revises: 286f6d5d5357
Create Date: 2025-08-24 20:46:10.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8b1a9c2e0d'
down_revision: Union[str, Sequence[str], None] = '286f6d5d5357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('prologue', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'prologue')
    # ### end Alembic commands ###