"""Add char_count and word_count to manuscript_blocks

Revision ID: 5665cc4fb703
Revises: 2d6637265762
Create Date: 2025-08-29 15:32:16.081659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5665cc4fb703'
down_revision: Union[str, Sequence[str], None] = '2d6637265762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscript_blocks', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('manuscript_blocks', sa.Column('char_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manuscript_blocks', 'char_count')
    op.drop_column('manuscript_blocks', 'word_count')
    # ### end Alembic commands ###
