"""Add indexes to foreign key columns for performance

Revision ID: eb3feabd6c5c
Revises: 15208e8d9a4a
Create Date: 2025-08-31 19:21:02.787166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3feabd6c5c'
down_revision: Union[str, Sequence[str], None] = '15208e8d9a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cards_group_id'), 'cards', ['group_id'], unique=False)
    op.create_index(op.f('ix_groups_project_id'), 'groups', ['project_id'], unique=False)
    op.create_index(op.f('ix_plot_points_scenario_id'), 'plot_points', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_relationships_project_id'), 'relationships', ['project_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_character_id'), 'relationships', ['source_character_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_character_id'), 'relationships', ['target_character_id'], unique=False)
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=False)
    op.create_index(op.f('ix_worldview_cards_group_id'), 'worldview_cards', ['group_id'], unique=False)
    op.create_index(op.f('ix_worldview_groups_project_id'), 'worldview_groups', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worldview_groups_project_id'), table_name='worldview_groups')
    op.drop_index(op.f('ix_worldview_cards_group_id'), table_name='worldview_cards')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_index(op.f('ix_relationships_target_character_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_character_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_project_id'), table_name='relationships')
    op.drop_index(op.f('ix_plot_points_scenario_id'), table_name='plot_points')
    op.drop_index(op.f('ix_groups_project_id'), table_name='groups')
    op.drop_index(op.f('ix_cards_group_id'), table_name='cards')
    # ### end Alembic commands ###
